/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CEU;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;


/**
 *
 * @author joaom
 */
public class frmRelatorios extends javax.swing.JFrame {

    
    OpBancoCadastroAluno ob = new OpBancoCadastroAluno();
    /**
     * Creates new form frmRelatorios
     */
    public frmRelatorios() {
        initComponents();
        iniciarLabels();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRelatorio = new javax.swing.ButtonGroup();
        jLabel4 = new javax.swing.JLabel();
        btnSair = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        cbCidade = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        btnImprimirCidade = new javax.swing.JButton();
        lblAssis = new javax.swing.JLabel();
        lblBandeirantes = new javax.swing.JLabel();
        lblJacarezinho = new javax.swing.JLabel();
        lbl4 = new javax.swing.JLabel();
        lblCornelio = new javax.swing.JLabel();
        lblOurinhos = new javax.swing.JLabel();
        lblSantoAntonio = new javax.swing.JLabel();
        lbl1 = new javax.swing.JLabel();
        lblCambara = new javax.swing.JLabel();
        lbl6 = new javax.swing.JLabel();
        lbl7 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        lbl3 = new javax.swing.JLabel();
        lbl5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbl8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel4.setText("Relatorios");

        btnSair.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnSair.setText("Sair");
        btnSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSairMousePressed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Relatorio por cidade"));

        cbCidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Assis", "Bandeirantes", "Cambara", "Cornelio Procopio", "Jacarezinho", "Ourinhos", "Santo Antonio da Platina" }));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setText("Escolha a cidade");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(cbCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnImprimirCidade.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnImprimirCidade.setText("Imprimir");
        btnImprimirCidade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnImprimirCidadeMousePressed(evt);
            }
        });

        lblAssis.setText("Assis");

        lblBandeirantes.setText("Bandeirantes");

        lblJacarezinho.setText("Jacarezinho");

        lbl4.setText("0");

        lblCornelio.setText("Cornelio Procopio");

        lblOurinhos.setText("Ourinhos");

        lblSantoAntonio.setText("Santo Antonio");

        lbl1.setText("0");

        lblCambara.setText("Cambara");

        lbl6.setText("0");

        lbl7.setText("0");

        lbl2.setText("0");

        lbl3.setText("0");

        lbl5.setText("0");

        jLabel2.setText("Total");

        lbl8.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(152, 152, 152))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnImprimirCidade)
                        .addGap(237, 237, 237))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbl8))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblOurinhos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbl6))
                            .addComponent(btnSair, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblBandeirantes)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbl2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblCornelio)
                                .addGap(18, 18, 18)
                                .addComponent(lbl4)))
                        .addGap(89, 89, 89))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCambara)
                                    .addComponent(lblAssis))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(35, 35, 35)
                                        .addComponent(lbl1))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lbl3))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblSantoAntonio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbl7))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblJacarezinho)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbl5))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAssis)
                    .addComponent(lbl1)
                    .addComponent(lbl2)
                    .addComponent(lblBandeirantes))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCornelio)
                    .addComponent(lblCambara)
                    .addComponent(lbl3)
                    .addComponent(lbl4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblJacarezinho)
                    .addComponent(lblOurinhos)
                    .addComponent(lbl6)
                    .addComponent(lbl5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSantoAntonio)
                    .addComponent(lbl7)
                    .addComponent(jLabel2)
                    .addComponent(lbl8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSair)
                    .addComponent(btnImprimirCidade))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSairMousePressed
        int resp = JOptionPane.showConfirmDialog(null, "Voce deseja sair?", "Pergunta", JOptionPane.YES_NO_OPTION);
        if(resp == JOptionPane.YES_OPTION){
            this.dispose();
        }
    }//GEN-LAST:event_btnSairMousePressed

    private void btnImprimirCidadeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnImprimirCidadeMousePressed
        
        
        
        String cidade = cbCidade.getSelectedItem().toString();
        
        
        ResultSet ls = ob.executarQuery("select * from aluno where cidade like '"+cidade+"' order by nome");
        JRResultSetDataSource relatResul = new JRResultSetDataSource(ls);
        try {
            JasperPrint jpPrint = JasperFillManager.fillReport("C:/Users/Servidor/Documents/NetBeansProjects/ProjetoCEU/Relatorios/Relatorio2.jasper", new HashMap(), relatResul);
            JasperViewer jv = new JasperViewer(jpPrint, false);
            jv.setVisible(true);

        } catch (JRException ex) {
            
            System.out.println("Erro: "+ex);
            
        }catch(NullPointerException ex){
            JOptionPane.showMessageDialog(null, "Erro! Não foi possivel gerar o relatorio", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnImprimirCidadeMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmRelatorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmRelatorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmRelatorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmRelatorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmRelatorios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnImprimirCidade;
    private javax.swing.ButtonGroup btnRelatorio;
    private javax.swing.JButton btnSair;
    private javax.swing.JComboBox<String> cbCidade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl4;
    private javax.swing.JLabel lbl5;
    private javax.swing.JLabel lbl6;
    private javax.swing.JLabel lbl7;
    private javax.swing.JLabel lbl8;
    private javax.swing.JLabel lblAssis;
    private javax.swing.JLabel lblBandeirantes;
    private javax.swing.JLabel lblCambara;
    private javax.swing.JLabel lblCornelio;
    private javax.swing.JLabel lblJacarezinho;
    private javax.swing.JLabel lblOurinhos;
    private javax.swing.JLabel lblSantoAntonio;
    // End of variables declaration//GEN-END:variables

    private void iniciarLabels() {
        
        ResultSet rs = null;
        int cont=0;
        //Assis
        rs = ob.buscarAlunoPorCidade("Assis");
        try {
            rs.last();
            cont = rs.getRow();
        } catch (SQLException ex) {
            Logger.getLogger(frmRelatorios.class.getName()).log(Level.SEVERE, null, ex);
        }
        //setando o numero de cont no label
        lbl1.setText(Integer.toString(cont));
        
        
        //Bandeirantes
        int cont2=0;
        rs = ob.buscarAlunoPorCidade("Bandeirantes");
        try {
            rs.last();
            cont2 = rs.getRow();
        } catch (SQLException ex) {
            Logger.getLogger(frmRelatorios.class.getName()).log(Level.SEVERE, null, ex);
        }
        //setando o numero de cont no label
        lbl2.setText(Integer.toString(cont2));
        
        //Cambara
        int cont3=0;
        rs = ob.buscarAlunoPorCidade("Cambara");
        try {
            rs.last();
            cont3 = rs.getRow();
        } catch (SQLException ex) {
            Logger.getLogger(frmRelatorios.class.getName()).log(Level.SEVERE, null, ex);
        }
        //setando o numero de cont no label
        lbl3.setText(Integer.toString(cont3));
        
        //Cornelio
        int cont4=0;
        rs = ob.buscarAlunoPorCidade("Cornelio Procopio");
        try {
            rs.last();
            cont4 = rs.getRow();
        } catch (SQLException ex) {
            Logger.getLogger(frmRelatorios.class.getName()).log(Level.SEVERE, null, ex);
        }
        //setando o numero de cont no label
        lbl4.setText(Integer.toString(cont4));
        
        //Jacaré
        int cont5=0;
        rs = ob.buscarAlunoPorCidade("Jacarezinho");
        try {
            rs.last();
            cont5 = rs.getRow();
        } catch (SQLException ex) {
            Logger.getLogger(frmRelatorios.class.getName()).log(Level.SEVERE, null, ex);
        }
        //setando o numero de cont no label
        lbl5.setText(Integer.toString(cont5));
        
        //Ourinhos
        int cont6=0;
        rs = ob.buscarAlunoPorCidade("Ourinhos");
        try {
            rs.last();
            cont6 = rs.getRow();
        } catch (SQLException ex) {
            Logger.getLogger(frmRelatorios.class.getName()).log(Level.SEVERE, null, ex);
        }
        //setando o numero de cont no label
        lbl6.setText(Integer.toString(cont6));
        
        //Santo Antonio da Platina
        int cont7=0;
        rs = ob.buscarAlunoPorCidade("Santo Antonio da Platina");
        try {
            rs.last();
            cont7 = rs.getRow();
        } catch (SQLException ex) {
            Logger.getLogger(frmRelatorios.class.getName()).log(Level.SEVERE, null, ex);
        }
        //setando o numero de cont no label
        lbl7.setText(Integer.toString(cont7));
        
        
        //Total de Cadastros
        int cont8=0;
        rs = ob.listarAlunos();
        try {
            rs.last();
            cont8 = rs.getRow();
        } catch (SQLException ex) {
            Logger.getLogger(frmRelatorios.class.getName()).log(Level.SEVERE, null, ex);
        }
        //setando o numero de cont no label
        lbl8.setText(Integer.toString(cont8));
    }

    
}
